/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ConditionRecordData, RecordData, RecordDataByDisease, VaccinationRecordData } from "./utils/recordData";
import { FilterCounts, FilterStates } from "./utils/recordFilters";
import { PatientDetails } from "./utils/patientData";
export { ConditionRecordData, RecordData, RecordDataByDisease, VaccinationRecordData } from "./utils/recordData";
export { FilterCounts, FilterStates } from "./utils/recordFilters";
export { PatientDetails } from "./utils/patientData";
export namespace Components {
    interface MioViewerImpfpass {
        "base64FhirData": string | string[];
    }
    interface MioViewerImpfpassConditionEntry {
        "condition": ConditionRecordData;
        "diseaseName": string;
    }
    interface MioViewerImpfpassConditionInformation {
        "infoHead": string;
        "infoText": string;
    }
    interface MioViewerImpfpassDismissableCard {
        "dismissMenuCallback": () => void;
    }
    interface MioViewerImpfpassExtraMenu {
    }
    interface MioViewerImpfpassFilterMenu {
        "filterCounts": FilterCounts;
        "initialFilterStates": FilterStates;
    }
    interface MioViewerImpfpassHeader {
        "patient": PatientDetails | undefined;
    }
    interface MioViewerImpfpassListSortIndicator {
        "active": boolean;
        "reversed": boolean;
    }
    interface MioViewerImpfpassPractitioner {
        "adress": string[];
        "organisationName": string;
        "practitioner": string;
        "qualification": string;
    }
    interface MioViewerImpfpassRecordList {
        "diseaseName": string;
        "recordDetails": RecordData[];
    }
    interface MioViewerImpfpassRecordOverview {
        "recordDataByDisease": RecordDataByDisease;
        "selectedDisease": string;
    }
    interface MioViewerImpfpassVaccinationEntry {
        "diseaseName": string;
        "vaccination": VaccinationRecordData;
    }
}
export interface MioViewerImpfpassConditionEntryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMioViewerImpfpassConditionEntryElement;
}
export interface MioViewerImpfpassFilterMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMioViewerImpfpassFilterMenuElement;
}
export interface MioViewerImpfpassPractitionerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMioViewerImpfpassPractitionerElement;
}
export interface MioViewerImpfpassRecordListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMioViewerImpfpassRecordListElement;
}
export interface MioViewerImpfpassRecordOverviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMioViewerImpfpassRecordOverviewElement;
}
declare global {
    interface HTMLMioViewerImpfpassElement extends Components.MioViewerImpfpass, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassElement: {
        prototype: HTMLMioViewerImpfpassElement;
        new (): HTMLMioViewerImpfpassElement;
    };
    interface HTMLMioViewerImpfpassConditionEntryElement extends Components.MioViewerImpfpassConditionEntry, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassConditionEntryElement: {
        prototype: HTMLMioViewerImpfpassConditionEntryElement;
        new (): HTMLMioViewerImpfpassConditionEntryElement;
    };
    interface HTMLMioViewerImpfpassConditionInformationElement extends Components.MioViewerImpfpassConditionInformation, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassConditionInformationElement: {
        prototype: HTMLMioViewerImpfpassConditionInformationElement;
        new (): HTMLMioViewerImpfpassConditionInformationElement;
    };
    interface HTMLMioViewerImpfpassDismissableCardElement extends Components.MioViewerImpfpassDismissableCard, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassDismissableCardElement: {
        prototype: HTMLMioViewerImpfpassDismissableCardElement;
        new (): HTMLMioViewerImpfpassDismissableCardElement;
    };
    interface HTMLMioViewerImpfpassExtraMenuElement extends Components.MioViewerImpfpassExtraMenu, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassExtraMenuElement: {
        prototype: HTMLMioViewerImpfpassExtraMenuElement;
        new (): HTMLMioViewerImpfpassExtraMenuElement;
    };
    interface HTMLMioViewerImpfpassFilterMenuElement extends Components.MioViewerImpfpassFilterMenu, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassFilterMenuElement: {
        prototype: HTMLMioViewerImpfpassFilterMenuElement;
        new (): HTMLMioViewerImpfpassFilterMenuElement;
    };
    interface HTMLMioViewerImpfpassHeaderElement extends Components.MioViewerImpfpassHeader, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassHeaderElement: {
        prototype: HTMLMioViewerImpfpassHeaderElement;
        new (): HTMLMioViewerImpfpassHeaderElement;
    };
    interface HTMLMioViewerImpfpassListSortIndicatorElement extends Components.MioViewerImpfpassListSortIndicator, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassListSortIndicatorElement: {
        prototype: HTMLMioViewerImpfpassListSortIndicatorElement;
        new (): HTMLMioViewerImpfpassListSortIndicatorElement;
    };
    interface HTMLMioViewerImpfpassPractitionerElement extends Components.MioViewerImpfpassPractitioner, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassPractitionerElement: {
        prototype: HTMLMioViewerImpfpassPractitionerElement;
        new (): HTMLMioViewerImpfpassPractitionerElement;
    };
    interface HTMLMioViewerImpfpassRecordListElement extends Components.MioViewerImpfpassRecordList, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassRecordListElement: {
        prototype: HTMLMioViewerImpfpassRecordListElement;
        new (): HTMLMioViewerImpfpassRecordListElement;
    };
    interface HTMLMioViewerImpfpassRecordOverviewElement extends Components.MioViewerImpfpassRecordOverview, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassRecordOverviewElement: {
        prototype: HTMLMioViewerImpfpassRecordOverviewElement;
        new (): HTMLMioViewerImpfpassRecordOverviewElement;
    };
    interface HTMLMioViewerImpfpassVaccinationEntryElement extends Components.MioViewerImpfpassVaccinationEntry, HTMLStencilElement {
    }
    var HTMLMioViewerImpfpassVaccinationEntryElement: {
        prototype: HTMLMioViewerImpfpassVaccinationEntryElement;
        new (): HTMLMioViewerImpfpassVaccinationEntryElement;
    };
    interface HTMLElementTagNameMap {
        "mio-viewer-impfpass": HTMLMioViewerImpfpassElement;
        "mio-viewer-impfpass-condition-entry": HTMLMioViewerImpfpassConditionEntryElement;
        "mio-viewer-impfpass-condition-information": HTMLMioViewerImpfpassConditionInformationElement;
        "mio-viewer-impfpass-dismissable-card": HTMLMioViewerImpfpassDismissableCardElement;
        "mio-viewer-impfpass-extra-menu": HTMLMioViewerImpfpassExtraMenuElement;
        "mio-viewer-impfpass-filter-menu": HTMLMioViewerImpfpassFilterMenuElement;
        "mio-viewer-impfpass-header": HTMLMioViewerImpfpassHeaderElement;
        "mio-viewer-impfpass-list-sort-indicator": HTMLMioViewerImpfpassListSortIndicatorElement;
        "mio-viewer-impfpass-practitioner": HTMLMioViewerImpfpassPractitionerElement;
        "mio-viewer-impfpass-record-list": HTMLMioViewerImpfpassRecordListElement;
        "mio-viewer-impfpass-record-overview": HTMLMioViewerImpfpassRecordOverviewElement;
        "mio-viewer-impfpass-vaccination-entry": HTMLMioViewerImpfpassVaccinationEntryElement;
    }
}
declare namespace LocalJSX {
    interface MioViewerImpfpass {
        "base64FhirData"?: string | string[];
    }
    interface MioViewerImpfpassConditionEntry {
        "condition"?: ConditionRecordData;
        "diseaseName"?: string;
        "onCloseInformation"?: (event: MioViewerImpfpassConditionEntryCustomEvent<any>) => void;
    }
    interface MioViewerImpfpassConditionInformation {
        "infoHead"?: string;
        "infoText"?: string;
    }
    interface MioViewerImpfpassDismissableCard {
        "dismissMenuCallback"?: () => void;
    }
    interface MioViewerImpfpassExtraMenu {
    }
    interface MioViewerImpfpassFilterMenu {
        "filterCounts"?: FilterCounts;
        "initialFilterStates"?: FilterStates;
        "onFiltersApplied"?: (event: MioViewerImpfpassFilterMenuCustomEvent<FilterStates>) => void;
    }
    interface MioViewerImpfpassHeader {
        "patient"?: PatientDetails | undefined;
    }
    interface MioViewerImpfpassListSortIndicator {
        "active"?: boolean;
        "reversed"?: boolean;
    }
    interface MioViewerImpfpassPractitioner {
        "adress"?: string[];
        "onClosePractitioner"?: (event: MioViewerImpfpassPractitionerCustomEvent<any>) => void;
        "organisationName"?: string;
        "practitioner"?: string;
        "qualification"?: string;
    }
    interface MioViewerImpfpassRecordList {
        "diseaseName"?: string;
        "onDetailsHidden"?: (event: MioViewerImpfpassRecordListCustomEvent<any>) => void;
        "recordDetails"?: RecordData[];
    }
    interface MioViewerImpfpassRecordOverview {
        "onDiseaseSelected"?: (event: MioViewerImpfpassRecordOverviewCustomEvent<string>) => void;
        "recordDataByDisease"?: RecordDataByDisease;
        "selectedDisease"?: string;
    }
    interface MioViewerImpfpassVaccinationEntry {
        "diseaseName"?: string;
        "vaccination"?: VaccinationRecordData;
    }
    interface IntrinsicElements {
        "mio-viewer-impfpass": MioViewerImpfpass;
        "mio-viewer-impfpass-condition-entry": MioViewerImpfpassConditionEntry;
        "mio-viewer-impfpass-condition-information": MioViewerImpfpassConditionInformation;
        "mio-viewer-impfpass-dismissable-card": MioViewerImpfpassDismissableCard;
        "mio-viewer-impfpass-extra-menu": MioViewerImpfpassExtraMenu;
        "mio-viewer-impfpass-filter-menu": MioViewerImpfpassFilterMenu;
        "mio-viewer-impfpass-header": MioViewerImpfpassHeader;
        "mio-viewer-impfpass-list-sort-indicator": MioViewerImpfpassListSortIndicator;
        "mio-viewer-impfpass-practitioner": MioViewerImpfpassPractitioner;
        "mio-viewer-impfpass-record-list": MioViewerImpfpassRecordList;
        "mio-viewer-impfpass-record-overview": MioViewerImpfpassRecordOverview;
        "mio-viewer-impfpass-vaccination-entry": MioViewerImpfpassVaccinationEntry;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mio-viewer-impfpass": LocalJSX.MioViewerImpfpass & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassElement>;
            "mio-viewer-impfpass-condition-entry": LocalJSX.MioViewerImpfpassConditionEntry & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassConditionEntryElement>;
            "mio-viewer-impfpass-condition-information": LocalJSX.MioViewerImpfpassConditionInformation & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassConditionInformationElement>;
            "mio-viewer-impfpass-dismissable-card": LocalJSX.MioViewerImpfpassDismissableCard & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassDismissableCardElement>;
            "mio-viewer-impfpass-extra-menu": LocalJSX.MioViewerImpfpassExtraMenu & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassExtraMenuElement>;
            "mio-viewer-impfpass-filter-menu": LocalJSX.MioViewerImpfpassFilterMenu & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassFilterMenuElement>;
            "mio-viewer-impfpass-header": LocalJSX.MioViewerImpfpassHeader & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassHeaderElement>;
            "mio-viewer-impfpass-list-sort-indicator": LocalJSX.MioViewerImpfpassListSortIndicator & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassListSortIndicatorElement>;
            "mio-viewer-impfpass-practitioner": LocalJSX.MioViewerImpfpassPractitioner & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassPractitionerElement>;
            "mio-viewer-impfpass-record-list": LocalJSX.MioViewerImpfpassRecordList & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassRecordListElement>;
            "mio-viewer-impfpass-record-overview": LocalJSX.MioViewerImpfpassRecordOverview & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassRecordOverviewElement>;
            "mio-viewer-impfpass-vaccination-entry": LocalJSX.MioViewerImpfpassVaccinationEntry & JSXBase.HTMLAttributes<HTMLMioViewerImpfpassVaccinationEntryElement>;
        }
    }
}
